### PR TITLE
Definition of BC related to language consistency

### PR DESCRIPTION
**Pull request by yellowbrickc**
I would like to add those definitions discussed on TW (and migrated here https://mastodon.social/@yellowbrickc/109409305173934197) to the Canvas because I think they are very valuable.

### CODE REVIEW

**Comment by mploed** [comment]
I think this is a valuable addition for the beginning.

I think mid-term we should also dig a bit deeper into this definition and explain what this actually means. The current text is very much targeted to people who have a fairly good understanding of DDD. However, I have the assumption, that a relevant amount of folks who look at this do not have this level of understanding and a more thourough explanation may be helpful in order to avoid misinterpretations.

**Review by mploed — APPROVED** [review]

**Comment by yellowbrickc** [comment]
@mploed Totally agree.

**Comment by NTCoding** [comment]
I could be wrong but I'm not that convinced the new definition is really helpful in isolation without explaining what things like unit of language consistency mean. 

Regarding the grammar it feels a little bit like ", a Unit of language consistency" has been bolted onto the first sentence where it doesn't logically follow (the first part of the sentence before the comma is not the definition of a unit of language consistency) and also I believe that "Unit" should be lower case.

Personally, I think it would be better to link to another resource, like a blog post, which explains the concept in more detail and defines the jargon with examples, rather than trying to force a definition into a single paragraph into this resource.

**Comment by yellowbrickc** [comment]
Oh, I'm sorry, I merged the PR because I thought you won't have time to answer, and I wanted to add these new definitions because of the nr. reactions to the discussion on TW and on mastodon. I didn't want to lose those, and I wanted to get some user feedback, just like you have proposed. OTOH I think we all agree that a blog post with more information would be better.

Proposal 1: I revert the commit and rephrase the sentence, but we include it and ask for feedback.
Proposal 2: I revert the commit, and we add it as soon as someone writes a post about it.

**Comment by NTCoding** [comment]
I would suggest keeping the current definition and fixing a couple of small grammar issues. There's nothing to be sorry about, it's important to keep evolving and improving the content and that involves trying out new things etc especially when the changes are easy to reverse. What you have done is totally correct.

**Comment by yellowbrickc** [comment]
continued in #35

**Pull request merged**
